# Generated by Django 4.2.2 on 2024-02-07 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                ("book_id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.TextField()),
                ("author", models.TextField()),
            ],
        ),
    ]
